name: CI with tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:    
  test:            
    runs-on: ubuntu-latest   

    steps:
    - uses: actions/checkout@v4    
    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"    
        
    - uses: snok/install-poetry@v1
      with:
        version: 1.8.0
        virtualenvs-create: false
        virtualenvs-in-project: true    

    - name: Install dependencies
      run: |
        cd src
        poetry install --no-interaction && \
          yes | poetry cache clear --all --no-interaction .
  
    - name: Run tests
      run: |
        cp .env.template src/.env
        cd src
        make types
        make format_check
        make lint_check
